name: Makefile CI
env: 
  GITHUB_TOKEN: ${{ secrets.PAT }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run test
      run: make test
